// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconLeft: typeof import('@icon-park/vue-next')['Left']
    IconPlus: typeof import('@icon-park/vue-next')['Plus']
    IconRight: typeof import('@icon-park/vue-next')['Right']
    IconSetting: typeof import('@icon-park/vue-next')['Setting']
    IconSettingConfig: typeof import('@icon-park/vue-next')['SettingConfig']
  }
}
