// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconSettingConfig: typeof import('@icon-park/vue-next')['SettingConfig']
    LoginDialog: typeof import('./src/components/login-dialog.vue')['default']
    SettingDialog: typeof import('./src/components/setting-dialog/index.vue')['default']
  }
}
